Subview toggle helper
mdiep/MDPSplitView pull request #20
Opened 2017-08-15 18:27 UTC by JanX2

2017-08-17 12:44 UTC, mdiep commented
Can you merge `master` into here so that the diff is updated? 🙏

2017-08-17 12:47 UTC, JanX2 commented
I can rebase. That’s cleaner I think. :)

2017-08-17 12:49 UTC, JanX2 commented
There.

2017-08-17 13:01 UTC, mdiep requested changes
I think it makes sense to include these helper methods, but I'd like to see a few changes:

1. Move these into the existing source files
2. Add full documentation for the methods
3. Match the existing style and indentation

(The xcodeproj is showing that it's configured for tabs for some reason, but the files are indented with spaces. Spaces are the desired indentation.)

2017-08-17 13:10 UTC, JanX2 commented
Will do. Friday at the earliest. Probably early next week. :)

2017-08-21 14:48 UTC, JanX2 commented
Done.

2017-08-23 13:02 UTC, mdiep requested changes

2017-08-23 13:02 UTC, mdiep commented on MDPSplitView.h
> + Whether you want to have the subview collapse rightward (or leftward, if NO).
Can you indent the descriptions? (To match the style above)

2017-08-23 15:50 UTC, JanX2 commented
Done.

BTW: I back-ported the Demo to Obj-C, if you ever are interested in that. I will not change anything style-related there, though. :D

2017-08-24 00:48 UTC, mdiep approved these changes

2017-08-24 00:49 UTC, merged

2017-08-24 00:49 UTC, mdiep commented
Thanks!